Repository kdoctor-io/kdoctor, pull requests merged in 2023-12, with the labels that each got.

#393 fix not read response body can't reuse connect
  pkg/loadRequest/loadHttp/http_requester.go
Labels: release/bug

#391 Modify labels and invalid references
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/call-release-pages.yaml
Labels: release/none

#396 Supports publishing rc versions of docs to dev
  .github/workflows/call-release-pages.yaml
Labels: documentation, release/none

#395 http client decreases to one connect pool for request
  charts/README.md
  charts/templates/configmap.yaml
  charts/values.yaml
  pkg/loadRequest/loadHttp/http.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/loadRequest/loadHttp/http_test.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  pkg/types/types.go
Labels: cherrypick-release-v0.2, release/feature-changed

#405 dns client use connect pool request
  charts/README.md
  charts/templates/configmap.yaml
  charts/values.yaml
  go.mod
  go.sum
  pkg/loadRequest/loadDns/dns.go
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadDns/dns_test.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/types/types.go
  vendor/github.com/ii2day/connexus/.gitignore
  vendor/github.com/ii2day/connexus/LICENSE
  vendor/github.com/ii2day/connexus/README.md
  vendor/github.com/ii2day/connexus/conn.go
  vendor/github.com/ii2day/connexus/heap.go
  vendor/github.com/ii2day/connexus/pool.go
  vendor/github.com/miekg/dns/LICENSE
  vendor/github.com/miekg/dns/README.md
  vendor/github.com/miekg/dns/acceptfunc.go
  vendor/github.com/miekg/dns/client.go
  vendor/github.com/miekg/dns/clientconfig.go
  vendor/github.com/miekg/dns/defaults.go
  vendor/github.com/miekg/dns/dnssec.go
  vendor/github.com/miekg/dns/dnssec_keyscan.go
  vendor/github.com/miekg/dns/doc.go
  vendor/github.com/miekg/dns/edns.go
  vendor/github.com/miekg/dns/fuzz.go
  vendor/github.com/miekg/dns/generate.go
  vendor/github.com/miekg/dns/labels.go
  vendor/github.com/miekg/dns/listen_no_reuseport.go
  vendor/github.com/miekg/dns/listen_reuseport.go
  vendor/github.com/miekg/dns/msg.go
  vendor/github.com/miekg/dns/msg_helpers.go
  vendor/github.com/miekg/dns/scan.go
  vendor/github.com/miekg/dns/scan_rr.go
  vendor/github.com/miekg/dns/server.go
  vendor/github.com/miekg/dns/singleinflight.go
  vendor/github.com/miekg/dns/svcb.go
  vendor/github.com/miekg/dns/tools.go
  vendor/github.com/miekg/dns/types.go
  vendor/github.com/miekg/dns/udp.go
  vendor/github.com/miekg/dns/udp_windows.go
  vendor/github.com/miekg/dns/version.go
  vendor/github.com/miekg/dns/xfr.go
  vendor/github.com/miekg/dns/zduplicate.go
  vendor/github.com/miekg/dns/zmsg.go
  vendor/github.com/miekg/dns/ztypes.go
  vendor/modules.txt
Labels: release/feature-changed

#407 update kind quick start
  docs/usage/get-started-kind-zh_CN.md
  docs/usage/get-started-kind.md
Labels: release/none, cherrypick-release-v0.2

#399 remove http-server-test chart
  charts/http-server-test-0.1.0.tgz
  index.yaml
Labels: release/none

#412 fix doc website
  docs/mkdocs.yml
Labels: release/none, cherrypick-release-v0.2

#415 update connexus to v0.1.3 to fix lock
  go.mod
  go.sum
  vendor/github.com/ii2day/connexus/pool.go
  vendor/modules.txt
Labels: release/none, cherrypick-release-v0.2

#408 http client decreases to one connect pool for request
  charts/README.md
  charts/templates/configmap.yaml
  charts/values.yaml
  pkg/loadRequest/loadHttp/http.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/loadRequest/loadHttp/http_test.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  pkg/types/types.go
Labels: robot-cherrypick

#417 update connexus to v0.1.4 to fix lock
  go.mod
  go.sum
  vendor/github.com/ii2day/connexus/pool.go
  vendor/modules.txt
Labels: release/none

#418 update connexus to v0.1.5 to fix sort nil
  go.mod
  go.sum
  vendor/github.com/ii2day/connexus/pool.go
  vendor/modules.txt
Labels: release/none

#423 docs: format docs
  docs/usage/get-started-kind-zh_CN.md
  docs/usage/get-started-kind.md
Labels: release/none

#427 docs: format docs
  docs/README-zh_CN.md
  docs/README.md
  docs/mkdocs.yml
  docs/reference/apphttphealthy-zh_CN.md
  docs/reference/apphttphealthy.md
  docs/reference/netreach-zh_CN.md
  docs/reference/netreach.md
  docs/reference/report.md
  docs/usage/apphttphealthy-zh_CN.md
  docs/usage/apphttphealthy.md
  docs/usage/debug-zh_CN.md
  docs/usage/debug.md
  docs/usage/get-started-kind-zh_CN.md
  docs/usage/get-started-kind.md
  docs/usage/netdns-zh_CN.md
  docs/usage/netdns.md
  docs/usage/netreach-zh_CN.md
  docs/usage/netreach.md
  docs/usage/performance.md
Labels: release/none, release/bug

#406 Enhance agent robustness in app mode && chart value optimization
  Makefile.defs
  cmd/agent/cmd/cert.go
  cmd/agent/cmd/daemon.go
  pkg/agentDnsServer/appDnsServer.go
  pkg/agentHttpServer/appHttpServer.go
  test/Makefile
  test/chart-app/Chart.yaml
  test/chart-app/templates/app.yaml
  test/chart-app/values.yaml
  test/e2e/apphttphealth/apphttphealth_test.go
Labels: release/feature-changed

#430 Optimize kdoctor reports for better readability
  pkg/apiserver/printers/table_generator.go
  pkg/apiserver/registry/kdoctor/kdoctorreport/etcd.go
  pkg/k8s/apis/system/v1beta1/apphttphealthy.go
  pkg/k8s/apis/system/v1beta1/common_types.go
  pkg/k8s/apis/system/v1beta1/kdoctorreport_types.go
  pkg/k8s/apis/system/v1beta1/netdns.go
  pkg/k8s/apis/system/v1beta1/netreach.go
  pkg/k8s/apis/system/v1beta1/zz_generated.deepcopy.go
  pkg/pluginManager/agentTools.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  pkg/pluginManager/types/types.go
  test/e2e/common/tools.go
Labels: release/feature-changed

#432 update connexus to v0.1.10 && Fixed the problem of directly discarding the request when the link is not obtained.
  go.mod
  go.sum
  pkg/loadRequest/loadDns/dns_requester.go
  vendor/github.com/ii2day/connexus/conn.go
  vendor/github.com/ii2day/connexus/pool.go
  vendor/modules.txt
Labels: release/bug

#445 fix ci upload artifact duplicate name
  .github/workflows/build-image-ci.yaml
  .github/workflows/call-release-image.yaml
Labels: release/none

#442 rename report name is kind + name
  docs/usage/apphttphealthy-zh_CN.md
  docs/usage/apphttphealthy.md
  docs/usage/netdns-zh_CN.md
  docs/usage/netdns.md
  docs/usage/netreach-zh_CN.md
  docs/usage/netreach.md
  pkg/apiserver/registry/kdoctor/kdoctorreport/etcd.go
  test/e2e/common/tools.go
Labels: release/feature-changed

#265 preformance
  docs/usage/performance.md
Labels: release/none

#448 change request token send interval
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadHttp/http_requester.go
  test/e2e/netdns/netdns_suite_test.go
Labels: release/feature-changed

#457 bump version to v0.2.2
  VERSION
  charts/Chart.yaml
  test/chart-app/Chart.yaml
Labels: release/none

#464 fix ci release
  .github/workflows/auto-release.yaml
Labels: release/none, cherrypick-release-v0.2

#465 fix ci release
  .github/workflows/auto-release.yaml
Labels: robot-cherrypick

#469 fix release ci kdoctor-test-server invalid
  .github/workflows/auto-release.yaml
Labels: release/none, cherrypick-release-v0.2

#470 fix release ci kdoctor-test-server invalid
  .github/workflows/auto-release.yaml
Labels: robot-cherrypick
