Repository kdoctor-io/kdoctor, pull requests merged in 2023-10, with the labels that each got.

#234 update version to v0.2.0-rc1
  VERSION
  charts/Chart.yaml
  test/chart-app/Chart.yaml
Labels: robot-cherrypick

#228 fix netdns success rate err
  pkg/pluginManager/netdns/agentExecuteTask.go
  test/e2e/common/tools.go
Labels: cherrypick-release-v0.2, release/bug

#230 fix task timeout no report
  pkg/pluginManager/agentTools.go
  test/docs/AppHttpHealth.md
  test/e2e/apphttphealth/apphttphealth_test.go
Labels: cherrypick-release-v0.2, release/bug

#200 fixed the netreach target configuration not taking effect
  pkg/k8s/apis/kdoctor.io/v1beta1/netreach_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/zz_generated.deepcopy.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/pluginManager/controllerReconciler.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  pkg/pluginManager/netreach/webhook.go
  pkg/scheduler/schedule.go
  test/e2e/apphttphealth/apphttphealth_test.go
  test/e2e/common/tools.go
  test/e2e/netdns/netdns_test.go
  test/e2e/netreach/netreach_test.go
  test/e2e/runtime/runtime_test.go
Labels: cherrypick-release-v0.2, release/bug

#246 fix netdns success rate error
  pkg/k8s/apis/kdoctor.io/v1beta1/netreach_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/zz_generated.deepcopy.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/pluginManager/agentTools.go
  pkg/pluginManager/controllerReconciler.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  pkg/pluginManager/netreach/webhook.go
  pkg/scheduler/schedule.go
  test/docs/AppHttpHealth.md
  test/e2e/apphttphealth/apphttphealth_test.go
  test/e2e/common/tools.go
  test/e2e/netdns/netdns_test.go
  test/e2e/netreach/netreach_test.go
  test/e2e/runtime/runtime_test.go
Labels: release/bug

#224 Increase the timeout time for e2e requests
  test/e2e/apphttphealth/apphttphealth_test.go
Labels: cherrypick-release-v0.2, release/feature-changed

#248 Increase the timeout time for e2e requests
  test/e2e/apphttphealth/apphttphealth_test.go
Labels: robot-cherrypick

#221 fix: qps is not correct
  pkg/agentDnsServer/appDnsServer.go
  pkg/k8s/apis/system/v1beta1/apphttphealthy.go
  pkg/k8s/apis/system/v1beta1/netdns.go
  pkg/loadRequest/loadDns/dns.go
  pkg/loadRequest/loadDns/dns_reporter.go
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadHttp/http.go
  pkg/loadRequest/loadHttp/http_reporter.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  test/Makefile
  test/docs/NetDns.md
  test/e2e/common/tools.go
  test/e2e/netdns/netdns_test.go
Labels: cherrypick-release-v0.2, release/bug

#254 increase netreach e2e timeout
  test/e2e/netreach/netreach_test.go
  test/e2e/runtime/runtime_test.go
Labels: release/none, cherrypick-release-v0.2

#263 update doc
  docs/concepts/runtime-zh_CN.md
  docs/reference/kdoctor-agent.md
  docs/reference/kdoctor-controller.md
  docs/usage/apphttphealthy-zh_CN.md
Labels: release/none

#275 chore: fix typo
  README-zh_CN.md
  cmd/agent/cmd/daemon.go
Labels: robot-cherrypick

#278 update version to v0.2.0
  VERSION
  charts/Chart.yaml
  test/chart-app/Chart.yaml
Labels: release/none, cherrypick-release-v0.2
