Repository kdoctor-io/kdoctor, pull requests merged in 2023-06, with the labels that each got.

#8 add https cert and body
  charts/crds/kdoctor.io_httpapphealthies.yaml
  charts/crds/kdoctor.io_netreachhealthies.yaml
  charts/templates/tls.yaml
  docs/usage/httpapphealthy.md
  docs/usage/netdns.md
  go.mod
  go.sum
  pkg/k8ObjManager/configmap.go
  pkg/k8ObjManager/manager.go
  pkg/k8ObjManager/secret.go
  pkg/k8s/apis/kdoctor.io/v1beta1/httpapphealthy_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/netreachhealthy_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/zz_generated.deepcopy.go
  pkg/loadRequest/loadHttp/http.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/lock/lock_debug_test.go
  pkg/lock/lock_fast_test.go
  pkg/pluginManager/httpapphealthy/agentExecuteTask.go
  pkg/pluginManager/httpapphealthy/webhook.go
  pkg/utils/utils.go
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/cryptobyte/builder.go
  vendor/modules.txt
Labels: enhancement

#21 update crd
  charts/crds/kdoctor.io_apphttphealthies.yaml
  charts/crds/kdoctor.io_netdnses.yaml
  charts/crds/kdoctor.io_netreaches.yaml
  docs/usage/apphttphealthy.md
  docs/usage/netdns.md
  docs/usage/netreach.md
  pkg/k8s/apis/kdoctor.io/v1beta1/apphttphealthy_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/common_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/netdns_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/netreach_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/zz_generated.deepcopy.go
  pkg/loadRequest/loadHttp/http.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/apphttphealthy/webhook.go
  pkg/pluginManager/netdns/agentExecuteTask.go
Labels: documentation, enhancement, release/feature

#36 chart: set tolerations
  charts/values.yaml
Labels: release/none

#47 robot Update doc from to branch github_pages
  docs/404.html
  docs/assets/images/favicon.png
  docs/assets/javascripts/bundle.b425cdc4.min.js
  docs/assets/javascripts/bundle.b425cdc4.min.js.map
  docs/assets/javascripts/lunr/min/lunr.ar.min.js
  docs/assets/javascripts/lunr/min/lunr.da.min.js
  docs/assets/javascripts/lunr/min/lunr.de.min.js
  docs/assets/javascripts/lunr/min/lunr.du.min.js
  docs/assets/javascripts/lunr/min/lunr.es.min.js
  docs/assets/javascripts/lunr/min/lunr.fi.min.js
  docs/assets/javascripts/lunr/min/lunr.fr.min.js
  docs/assets/javascripts/lunr/min/lunr.hi.min.js
  docs/assets/javascripts/lunr/min/lunr.hu.min.js
  docs/assets/javascripts/lunr/min/lunr.hy.min.js
  docs/assets/javascripts/lunr/min/lunr.it.min.js
  docs/assets/javascripts/lunr/min/lunr.ja.min.js
  docs/assets/javascripts/lunr/min/lunr.jp.min.js
  docs/assets/javascripts/lunr/min/lunr.kn.min.js
  docs/assets/javascripts/lunr/min/lunr.ko.min.js
  docs/assets/javascripts/lunr/min/lunr.multi.min.js
  docs/assets/javascripts/lunr/min/lunr.nl.min.js
  docs/assets/javascripts/lunr/min/lunr.no.min.js
  docs/assets/javascripts/lunr/min/lunr.pt.min.js
  docs/assets/javascripts/lunr/min/lunr.ro.min.js
  docs/assets/javascripts/lunr/min/lunr.ru.min.js
  docs/assets/javascripts/lunr/min/lunr.sa.min.js
  docs/assets/javascripts/lunr/min/lunr.stemmer.support.min.js
  docs/assets/javascripts/lunr/min/lunr.sv.min.js
  docs/assets/javascripts/lunr/min/lunr.ta.min.js
  docs/assets/javascripts/lunr/min/lunr.te.min.js
  docs/assets/javascripts/lunr/min/lunr.th.min.js
  docs/assets/javascripts/lunr/min/lunr.tr.min.js
  docs/assets/javascripts/lunr/min/lunr.vi.min.js
  docs/assets/javascripts/lunr/min/lunr.zh.min.js
  docs/assets/javascripts/lunr/tinyseg.js
  docs/assets/javascripts/lunr/wordcut.js
  docs/assets/javascripts/workers/search.208ed371.min.js
  docs/assets/javascripts/workers/search.208ed371.min.js.map
  docs/assets/stylesheets/main.26e3688c.min.css
  docs/assets/stylesheets/main.26e3688c.min.css.map
  docs/assets/stylesheets/palette.ecc896b0.min.css
  docs/assets/stylesheets/palette.ecc896b0.min.css.map
  docs/charts/kdoctor-0.1.0-rc0.tgz
  docs/develop/crd/index.html
  docs/develop/dev/index.html
  docs/develop/release/index.html
  docs/develop/roadmap/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/read
  docs/reference/arch/index.html
  docs/reference/report/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/apphttphealthy/index.html
  docs/usage/install/index.html
  docs/usage/netdns/index.html
  docs/usage/netreach/index.html
  docs/usage/performance/index.html
Labels: pr/robot_update

#46 robot update changelog with tag v0.1.0-rc0 to branch github_pages
  changelogs/changelog_from_v0.0.0_to_v0.1.0-rc0.md
Labels: pr/robot_update
