Repository kdoctor-io/kdoctor, pull requests merged in 2023-11, with the labels that each got.

#273 add qps stats in report
  charts/crds/kdoctor.io_netdnses.yaml
  pkg/k8s/apis/kdoctor.io/v1beta1/netdns_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/zz_generated.deepcopy.go
  pkg/k8s/apis/system/v1beta1/apphttphealthy.go
  pkg/k8s/apis/system/v1beta1/common_types.go
  pkg/k8s/apis/system/v1beta1/netdns.go
  pkg/k8s/apis/system/v1beta1/netreach.go
  pkg/k8s/apis/system/v1beta1/zz_generated.deepcopy.go
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/pluginManager/agentManager.go
  pkg/pluginManager/agentReconciler.go
  pkg/pluginManager/agentTools.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netdns/webhook.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  pkg/pluginManager/types/types.go
  pkg/resource/resource.go
  pkg/runningTask/runningTask.go
  test/docs/AppHttpHealth.md
  test/e2e/apphttphealth/apphttphealth_test.go
  test/e2e/common/tools.go
  test/e2e/netdns/netdns_test.go
  test/e2e/runtime/runtime_test.go
  test/scripts/debugCluster.sh
Labels: release/feature-new

#307 update readme.md
  README-zh_CN.md
  docs/develop/contributing.md
  docs/images/arch.png
Labels: release/none

#306 [#303]fix-Failed_to_get_the_dns_service_IP_list
  pkg/agentDnsServer/appDnsServer.go
  pkg/k8ObjManager/service.go
  pkg/types/agent_config.go
Labels: release/bug

#304 report resource add mean cpu
  pkg/k8s/apis/system/v1beta1/common_types.go
  pkg/resource/resource.go
Labels: release/feature-new

#313 Publish development documents through github actions.
  .github/workflows/call-release-pages.yaml
Labels: documentation, release/none

#334 fix http client timeout param error
  pkg/loadRequest/loadHttp/http_requester.go
Labels: release/bug

#341 use new dns client to fix data race and reuse connect
  go.mod
  go.sum
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadDns/dns_test.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/resource/resource.go
  test/Makefile
  test/e2e/apphttphealth/apphttphealth_test.go
  test/e2e/common/constants.go
  test/e2e/common/tools.go
  test/e2e/netdns/netdns_test.go
  test/e2e/netreach/netreach_test.go
  test/e2e/runtime/runtime_test.go
  vendor/github.com/miekg/dns/LICENSE
  vendor/github.com/miekg/dns/README.md
  vendor/github.com/miekg/dns/acceptfunc.go
  vendor/github.com/miekg/dns/client.go
  vendor/github.com/miekg/dns/clientconfig.go
  vendor/github.com/miekg/dns/defaults.go
  vendor/github.com/miekg/dns/dnssec.go
  vendor/github.com/miekg/dns/dnssec_keyscan.go
  vendor/github.com/miekg/dns/doc.go
  vendor/github.com/miekg/dns/edns.go
  vendor/github.com/miekg/dns/fuzz.go
  vendor/github.com/miekg/dns/generate.go
  vendor/github.com/miekg/dns/labels.go
  vendor/github.com/miekg/dns/listen_no_reuseport.go
  vendor/github.com/miekg/dns/listen_reuseport.go
  vendor/github.com/miekg/dns/msg.go
  vendor/github.com/miekg/dns/msg_helpers.go
  vendor/github.com/miekg/dns/scan.go
  vendor/github.com/miekg/dns/scan_rr.go
  vendor/github.com/miekg/dns/server.go
  vendor/github.com/miekg/dns/singleinflight.go
  vendor/github.com/miekg/dns/svcb.go
  vendor/github.com/miekg/dns/tools.go
  vendor/github.com/miekg/dns/types.go
  vendor/github.com/miekg/dns/udp.go
  vendor/github.com/miekg/dns/udp_windows.go
  vendor/github.com/miekg/dns/version.go
  vendor/github.com/miekg/dns/xfr.go
  vendor/github.com/miekg/dns/zduplicate.go
  vendor/github.com/miekg/dns/zmsg.go
  vendor/github.com/miekg/dns/ztypes.go
  vendor/modules.txt
Labels: release/bug

#310 add debug doc
  docs/README-zh_CN.md
  docs/README.md
  docs/usage/debug-zh_CN.md
  docs/usage/debug.md
Labels: documentation, release/none

#347 dns client udp connect read and write will not time out
  go.mod
  go.sum
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadHttp/http_requester.go
  test/e2e/common/tools.go
  test/e2e/netreach/netreach_test.go
  vendor/github.com/miekg/dns/client.go
  vendor/modules.txt
Labels: release/bug

#348 doc
  docs/mkdocs.yml
  docs/usage/apphttphealthy-zh_CN.md
  docs/usage/apphttphealthy.md
  docs/usage/debug-zh_CN.md
  docs/usage/debug.md
  docs/usage/netdns-zh_CN.md
  docs/usage/netdns.md
  docs/usage/netreach-zh_CN.md
  docs/usage/netreach.md
  pkg/k8s/apis/system/v1beta1/common_types.go
Labels: release/none

#353 Add request token sending counter
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadHttp/http_requester.go
Labels: release/bug

#352 add e2e
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadHttp/http_requester.go
  test/docs/NetDns.md
  test/docs/Schedule.md
  test/e2e/apphttphealth/apphttphealth_test.go
  test/e2e/netdns/netdns_test.go
  test/e2e/netreach/netreach_test.go
Labels: release/none

#363 add http trace log
  pkg/loadRequest/loadHttp/http_requester.go
Labels: release/none

#364 add took lock time threshold to 0.5
  pkg/lock/lock_debug.go
Labels: release/none

#360 Add log and optimize e2e environment
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  test/Makefile
  test/e2e/apphttphealth/apphttphealth_test.go
Labels: release/none

#368 fix httptrace data race && add e2e
  pkg/loadRequest/loadHttp/http_requester.go
  test/docs/NetDns.md
  test/e2e/apphttphealth/apphttphealth_test.go
  test/e2e/netdns/netdns_test.go
  test/e2e/netreach/netreach_test.go
Labels: release/bug

#370 add kdoctor icon
  charts/Chart.yaml
  docs/images/kdoctor.svg
Labels: release/none

#372 fix report wrong time
  pkg/apiserver/registry/kdoctor/kdoctorreport/etcd.go
Labels: release/bug

#371 add dynamic request worker number
  charts/README.md
  charts/values.yaml
  docs/usage/debug-zh_CN.md
  docs/usage/debug.md
  pkg/loadRequest/loadDns/dns.go
  pkg/loadRequest/loadDns/dns_suite_test.go
  pkg/loadRequest/loadDns/dns_test.go
  pkg/loadRequest/loadHttp/http.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/loadRequest/loadHttp/http_suite_test.go
  pkg/loadRequest/loadHttp/http_test.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/apphttphealthy/webhook.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netdns/webhook.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  pkg/pluginManager/netreach/webhook.go
  pkg/types/types.go
Labels: release/feature-changed

#374 typo: fix configmap field error
  charts/README.md
  charts/templates/configmap.yaml
  charts/values.yaml
  pkg/types/types.go
Labels: release/none

#376 Fix configmap missing fields
  charts/templates/configmap.yaml
Labels: release/none

#378 Modify default qps limit university
  charts/README.md
  charts/values.yaml
  test/Makefile
Labels: release/none

#379 update version to v0.2.1
  VERSION
  charts/Chart.yaml
  test/chart-app/Chart.yaml
Labels: release/none

#386 remove http trace log
  pkg/loadRequest/loadHttp/http_requester.go
Labels: cherrypick-release-v0.2, release/bug

#387 remove http trace log
  pkg/loadRequest/loadHttp/http_requester.go
Labels: robot-cherrypick
