Repository kdoctor-io/kdoctor, pull requests merged in 2023-07, with the labels that each got.

#66 rename aggregation API name
  pkg/apiserver/apiserver.go
  pkg/apiserver/printers/table_generator.go
  pkg/apiserver/registry/kdoctor/kdoctorreport/etcd.go
  pkg/apiserver/registry/kdoctor/kdoctorreport/keyer.go
  pkg/apiserver/registry/kdoctor/kdoctorreport/strategy.go
  pkg/apiserver/registry/kdoctor/pluginreport/strategy.go
  pkg/k8s/apis/system/v1beta1/kdoctorreport_types.go
  pkg/k8s/apis/system/v1beta1/register.go
  pkg/k8s/apis/system/v1beta1/zz_generated.deepcopy.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netreach/agentExecuteTask.go
Labels: release/feature

#80 Add license 、origin link and changes of vendor code
  pkg/loadRequest/loadDns/dns.go
  pkg/loadRequest/loadDns/dns_reporter.go
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadHttp/http.go
  pkg/loadRequest/loadHttp/http_reporter.go
  pkg/loadRequest/loadHttp/http_requester.go
Labels: release/none

#90 Fixed the failure of installation of lower version k8s if the app is …
  test/chart-app/templates/app.yaml
Labels: release/none

#77 add latency switch
  charts/crds/kdoctor.io_apphttphealthies.yaml
  charts/crds/kdoctor.io_netdnses.yaml
  charts/crds/kdoctor.io_netreaches.yaml
  pkg/k8s/apis/kdoctor.io/v1beta1/apphttphealthy_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/netdns_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/netreach_types.go
  pkg/loadRequest/loadDns/dns.go
  pkg/loadRequest/loadDns/dns_reporter.go
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadDns/dns_test.go
  pkg/loadRequest/loadHttp/http.go
  pkg/loadRequest/loadHttp/http_reporter.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netreach/agentExecuteTask.go
Labels: release/feature

#93 fix apphttphealthy webhhok host and fix miss mean latency
  pkg/loadRequest/loadDns/dns_reporter.go
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadHttp/http_reporter.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/pluginManager/tools/tools.go
  test/e2e/apphttphealth/apphttphealth_test.go
Labels: release/none

#79 add agent app mode dns server
  api/v1/agentServer/models/echo_res.go
  api/v1/agentServer/openapi.yaml
  api/v1/agentServer/server/embedded_spec.go
  cmd/agent/cmd/daemon.go
  pkg/agentDnsServer/appDnsServer.go
  pkg/agentHttpServer/appHttpServer.go
  pkg/agentHttpServer/healthHttpServer.go
  pkg/loadRequest/loadDns/dns.go
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/types/agent_config.go
  test/Makefile
  test/chart-app/templates/app.yaml
  test/chart-app/templates/service.yaml
  test/chart-app/values.yaml
  test/docs/NetDns.md
  test/e2e/apphttphealth/apphttphealth_test.go
  test/e2e/common/constants.go
  test/e2e/common/tools.go
  test/e2e/netdns/netdns_suite_test.go
  test/e2e/netdns/netdns_test.go
Labels: release/feature

#98 fix ci golang lint
  pkg/agentHttpServer/appHttpServer.go
  test/e2e/netdns/netdns_suite_test.go
Labels: release/none

#107 add e2e cover
  test/docs/AppHttpHealth.md
  test/docs/NetDns.md
  test/docs/NetReach.md
  test/docs/Schedule.md
  test/docs/schedule.md
  test/e2e/apphttphealth/apphttphealth_test.go
  test/e2e/netdns/netdns_test.go
  test/e2e/netreach/netreach_test.go
  tools/scripts/e2ecover.sh
Labels: release/none

#106 add app chart ci
  Makefile
Labels: release/none

#110 Remove the QPS limit for CRDs
  charts/crds/kdoctor.io_apphttphealthies.yaml
  charts/crds/kdoctor.io_netdnses.yaml
  charts/crds/kdoctor.io_netreaches.yaml
  pkg/k8s/apis/kdoctor.io/v1beta1/common_types.go
  pkg/k8s/apis/kdoctor.io/v1beta1/netdns_types.go
Labels: release/none

#108 update kdoctor verion to v0.1.0
  VERSION
  charts/Chart.yaml
  test/chart-app/Chart.yaml
Labels: release/none

#105 doc: add zh_CN doc
  charts/values.yaml
  docs/mkdocs.yml
  docs/reference/apphttphealthy-zh_CN.md
  docs/reference/netdns-zh_CN.md
  docs/reference/netreach-zh_CN.md
  docs/usage/install-zh_CN.md
  pkg/pluginManager/tools/tools.go
Labels: release/none

#115 robot update changelog with tag v0.1.0 to branch github_pages
  changelogs/changelog_from_v0.0.0_to_v0.1.0.md
Labels: pr/robot_update

#120 robot Update doc from to branch github_pages
  docs/404.html
  docs/charts/http-server-test-0.1.0.tgz
  docs/charts/kdoctor-0.1.0.tgz
  docs/develop/crd/index.html
  docs/develop/dev/index.html
  docs/develop/release/index.html
  docs/develop/roadmap/index.html
  docs/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/reference/_example/index.html
  docs/reference/apphttphealthy-zh_CN/index.html
  docs/reference/arch/index.html
  docs/reference/netdns-zh_CN/index.html
  docs/reference/netreach-zh_CN/index.html
  docs/reference/report/index.html
  docs/sitemap.xml.gz
  docs/usage/_feature_example/index.html
  docs/usage/_install_example/index.html
  docs/usage/apphttphealthy/index.html
  docs/usage/install-zh_CN/index.html
  docs/usage/install/index.html
  docs/usage/netdns/index.html
  docs/usage/netreach/index.html
  docs/usage/performance/index.html
Labels: pr/robot_update
