Repository kdoctor-io/kdoctor, pull requests merged in 2023-09, with the labels that each got.

#176 robot update changelog with tag v0.2.0-rc0 to branch github_pages
  changelogs/changelog_from_v0.1.0_to_v0.2.0-rc0.md
Labels: pr/robot_update

#177 add doc multiversion for kdoctor
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-pages.yaml
  docs/mkdocs.yml
  docs/overrides/main.html
  test/e2e/common/tools.go
Labels: pr/not-ready, release/feature-new

#181 add doc multiversion for kdoctor
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-pages.yaml
  docs/mkdocs.yml
  docs/overrides/main.html
  test/e2e/common/tools.go
Labels: enhancement, release/none, cherrypick-release-v0.2

#178 add e2e test server install
  Makefile
  Makefile.defs
  test/Makefile
  test/e2e/apphttphealth/apphttphealth_suite_test.go
  test/e2e/apphttphealth/apphttphealth_test.go
  test/e2e/common/constants.go
  test/e2e/common/tools.go
  test/e2e/netdns/netdns_suite_test.go
Labels: release/none

#187 Adjust directory structure
  charts/http-server-test-0.1.0.tgz
  charts/kdoctor-0.1.0-rc0.tgz
  charts/kdoctor-0.1.0.tgz
  charts/kdoctor-0.2.0-rc0.tgz
  charts/server-0.2.0-rc0.tgz
  index.yaml
Labels: release/feature-changed

#186 Decoupling chart and website
  .github/workflows/auto-release.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-pages.yaml
Labels: cherrypick-release-v0.1, release/feature-changed

#190 Fix release-v0.1 documentation site bug
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-release.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-pages.yaml
  docs/README-zh_CN.md
  docs/README.md
  docs/mkdocs.yml
  docs/overrides/main.html
  test/e2e/common/tools.go
Labels: release/bug, release/feature-changed

#207 fix after task done ,http client idle connections not close
  pkg/loadRequest/loadHttp/http_requester.go
Labels: cherrypick-release-v0.2, release/bug

#217 http client optimizes memory
  pkg/loadRequest/loadHttp/http_requester.go
Labels: release/feature-new, cherrypick-release-v0.2

#226 resource stats
  cmd/agent/cmd/daemon.go
  pkg/pluginManager/agentTools.go
  pkg/pluginManager/apphttphealthy/agentExecuteTask.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netreach/agentExecuteTask.go
  pkg/pluginManager/types/types.go
  pkg/resource/resource.go
Labels: release/feature-new, cherrypick-release-v0.2

#233 update version to v0.2.0-rc1
  VERSION
  charts/Chart.yaml
  test/chart-app/Chart.yaml
Labels: release/none, cherrypick-release-v0.2
